language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nilutpalboruah/practice-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nilutpalboruah/practice-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "practice-docker-react"
  env: "Practicedockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-846157886950"
  bucket_path: "practice-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
